#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Vercel <-> Supabase preview branches"

# ── Stage 1: what we are wiring together ──────────────────────────────────
stage "Confirm the pieces"
say "Supabase branching already gives each PR its own database. This wizard"
say "makes the Vercel preview deployment build against that branch instead of"
say "against production."
say ""
say "Two things must already be true, and both are:"
step "The Vercel GitHub integration is connected (Vercel builds your PRs)."
step "Supabase branching is enabled."

if [ -f .env ]; then
  SUPABASE_PROJECT_ID=$(sed -n 's/^SUPABASE_PROJECT_ID=//p' .env | tr -d '"' | head -1)
fi
ask SUPABASE_PROJECT_ID "Supabase project ref (production):"
write_env SUPABASE_PROJECT_ID "$SUPABASE_PROJECT_ID"

say ""
say "Checking branching is live..."
if npx supabase branches list --project-ref "$SUPABASE_PROJECT_ID" >/dev/null 2>&1; then
  printf '  %s✓ branching is enabled%s\n' "$GREEN" "$RESET"
else
  warn "Could not confirm branching. Run 'deno task setup-branching' first."
  SKIPPED+=("confirm branching on $SUPABASE_PROJECT_ID")
fi

ask VERCEL_PROJECT "Vercel project name (e.g. roorooroo):"
ask VERCEL_TEAM "Vercel team/account slug (e.g. johnstonmatts-projects):"
pause "Ready to install the integration?"

# ── Stage 2: install the integration ──────────────────────────────────────
stage "Vercel — install the Supabase integration"
say "This is the 'connect an existing project' integration."
warn "Do NOT use the Vercel Marketplace 'create a Supabase project' flow."
note "That provisions a NEW, Vercel-billed project. You already have one, and"
note "it does not document preview-branch syncing."
open_url "https://vercel.com/integrations/supabase"
step "Click 'Add Integration' (or 'Manage' if it is already installed)."
step "Choose the account/team that owns '$VERCEL_PROJECT'."
step "Scope it to the '$VERCEL_PROJECT' project (or all projects)."
pause "Installed?"

# ── Stage 3: connect the two projects ─────────────────────────────────────
stage "Supabase — connect the project to Vercel"
say "The integration only syncs once the two projects are explicitly linked."
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_ID}/settings/integrations"
step "Find the Vercel section and add a connection."
step "Pick the Vercel project '$VERCEL_PROJECT'."
step "Enable syncing environment variables for preview deployments."
note "Supabase then writes NEXT_PUBLIC_SUPABASE_URL and"
note "NEXT_PUBLIC_SUPABASE_ANON_KEY (plus SUPABASE_* and POSTGRES_*) into"
note "Vercel, scoped to the preview deployment for each PR."
pause "Connected?"

# ── Stage 4: hand Preview scope to the integration ────────────────────────
stage "Vercel — stop overriding the synced values"
say "Your project already sets these by hand. A manual value scoped to Preview"
say "will shadow what the integration syncs, so the preview would keep pointing"
say "at production. Re-scope them to Production only."
open_url "https://vercel.com/${VERCEL_TEAM}/${VERCEL_PROJECT}/settings/environment-variables"
step "NEXT_PUBLIC_SUPABASE_URL      -> uncheck Preview, keep Production."
step "NEXT_PUBLIC_SUPABASE_ANON_KEY -> uncheck Preview, keep Production."
say ""
step "NEXT_PUBLIC_API_BASE_URL       -> uncheck Preview, KEEP Production."
warn "Do not delete this one."
note "Production serves the API from the custom domain api.roorooroo.com, not"
note "from <ref>.supabase.co, so Production must keep its explicit value."
note "Unset on Preview, frontend/lib/api-client.ts derives the URL from"
note "NEXT_PUBLIC_SUPABASE_URL instead -- which the integration points at the"
note "branch. That matters because auth and the Edge Function must come from"
note "the SAME project: the function verifies the browser's JWT against that"
note "project's JWKS, so a mismatched pair 401s on every authenticated call."
note "Leaving a Preview value here pins previews to production's function,"
note "whose CORS allowlist rejects *.vercel.app origins outright."
pause "Done?"

# ── Stage 5: the vars the integration does not manage ─────────────────────
stage "Vercel — set what Supabase does not sync"
say "The integration only syncs Supabase's own credentials. This app reads two"
say "more variables that it knows nothing about."
open_url "https://vercel.com/${VERCEL_TEAM}/${VERCEL_PROJECT}/settings/environment-variables"
step "NEXT_PUBLIC_ALLOWED_SIGNUP_DOMAIN -> supabase.io, all environments."
note "Without it, signup on a preview falls back to the in-code default."
step "NEXT_PUBLIC_ALLOWED_SIGNUP_EMAILS -> only if you use the allowlist."
pause "Set?"

# ── Stage 6: fire the sync ────────────────────────────────────────────────
stage "Trigger the sync and verify"
say "Supabase syncs the variables when a pull request is OPENED, not when the"
say "branch is created. Any PR already open predates the connection and will"
say "not pick it up from a plain push -- it needs a fresh open event."
say ""
ask PR_NUMBER "PR number to re-trigger (blank to skip):"
if [ -n "${PR_NUMBER:-}" ] && command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if confirm "Close and reopen PR #${PR_NUMBER}? (notifies subscribers)"; then
    if gh pr close "$PR_NUMBER" && gh pr reopen "$PR_NUMBER"; then
      printf '  %s✓ reopened PR #%s%s\n' "$GREEN" "$PR_NUMBER" "$RESET"
    else
      warn "could not reopen PR #$PR_NUMBER -- do it in the browser"
      SKIPPED+=("close/reopen PR #$PR_NUMBER")
    fi
  else
    SKIPPED+=("close/reopen PR #$PR_NUMBER to trigger the first sync")
  fi
elif [ -n "${PR_NUMBER:-}" ]; then
  SKIPPED+=("close/reopen PR #$PR_NUMBER (gh not ready)")
fi

say ""
say "Verify once the redeploy finishes:"
step "Open the PR's Vercel preview and view source."
step "The Supabase host in the bundle should be the PREVIEW branch ref,"
step "not ${SUPABASE_PROJECT_ID}."
note "Supabase redeploys the PR's most recent deployment after syncing, so the"
note "first build of a PR can still be the stale one. Check the newest."

finish
