#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "Supabase branching + StackBlitz pr.new"

# ── Stage 1: project ref ──────────────────────────────────────────────────
stage "Supabase — which project"
say "Branching attaches to one Supabase project. We need its reference id."
open_url "https://supabase.com/dashboard/project/_/settings/general"
step "Pick the project this repo deploys to."
step "Copy the 'Project ID' (also called the reference id)."
ask SUPABASE_PROJECT_ID "Paste the project ref:"
write_env SUPABASE_PROJECT_ID "$SUPABASE_PROJECT_ID"

# The CLI supports named profiles, each with its own Management API token in
# the OS keyring. Verifying against the wrong one returns a bare 401.
ACTIVE_PROFILE=""
[ -f "$HOME/.supabase/profile" ] && ACTIVE_PROFILE=$(tr -d '\n' < "$HOME/.supabase/profile")
if [ -n "$ACTIVE_PROFILE" ]; then
  say ""
  note "Active Supabase CLI profile: $ACTIVE_PROFILE"
  ask SUPABASE_PROFILE "Profile to use for this project [Enter for $ACTIVE_PROFILE]:"
  [ -z "$SUPABASE_PROFILE" ] && SUPABASE_PROFILE="$ACTIVE_PROFILE"
else
  SUPABASE_PROFILE=""
fi

pause "Press Enter to connect GitHub."

# ── Stage 2: GitHub integration ───────────────────────────────────────────
stage "Supabase — connect the GitHub integration"
say "Branching is driven by the GitHub integration: it watches PRs and creates"
say "a preview branch for each one."
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_ID}/settings/integrations"
step "Find 'GitHub' and click Connect (authorize Supabase if prompted)."
step "Select the repository: johnstonmatt/roorooroo-app"
step "Set the supabase directory to: supabase"
step "Set the production branch to: main"
note "The directory must be 'supabase' -- that is where migrations/ and config.toml live."
pause "Done? Press Enter."

# ── Stage 3: enable branching ─────────────────────────────────────────────
stage "Supabase — turn branching on"
say "Preview branches are separate, billable Postgres instances. They are"
say "created per PR and destroyed when the PR closes."
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_ID}/branches"
step "Click 'Enable branching'."
step "Confirm the production branch is 'main'."
warn "Each running preview branch bills at the same hourly rate as a project."
note "Check current pricing at https://supabase.com/pricing before enabling on a busy repo."
pause "Enabled? Press Enter."

# ── Stage 4: the pr.new bot ───────────────────────────────────────────────
stage "StackBlitz — install the CodeflowApp bot"
say "This is the other half: it comments a one-click link that boots the PR"
say "in a browser IDE."
open_url "https://stackblitz.com/install-github-app"
step "Choose your account or org."
step "Grant access to johnstonmatt/roorooroo-app (or all repositories)."
note "Bot behaviour is configured in .stackblitz/codeflow.json, already committed."
pause "Installed? Press Enter to verify."

# ── Stage 5: verify ───────────────────────────────────────────────────────
stage "Verify"
say "Checking the pieces the preview-env workflow depends on."

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  secrets=$(gh secret list --json name --jq '.[].name' 2>/dev/null || echo "")
  for required in SUPABASE_ACCESS_TOKEN SUPABASE_PROJECT_ID; do
    if printf '%s\n' "$secrets" | grep -qx "$required"; then
      printf '  %s✓%s repo secret %s is set\n' "$GREEN" "$RESET" "$required"
    else
      warn "repo secret $required is MISSING"
      SKIPPED+=("GitHub secret $required (gh secret set $required)")
    fi
  done
else
  warn "gh unavailable -- could not check repository secrets"
  SKIPPED+=("verify GitHub secrets SUPABASE_ACCESS_TOKEN and SUPABASE_PROJECT_ID")
fi

say ""
say "Asking Supabase whether branching is live..."
[ -n "$SUPABASE_PROFILE" ] && note "using profile: $SUPABASE_PROFILE"

# Passing --profile only when set: macOS ships bash 3.2, where expanding an
# empty array under `set -u` is an unbound-variable error.
branches_list() {
  if [ -n "$SUPABASE_PROFILE" ]; then
    npx supabase branches list --project-ref "$SUPABASE_PROJECT_ID" --profile "$SUPABASE_PROFILE" 2>&1
  else
    npx supabase branches list --project-ref "$SUPABASE_PROJECT_ID" 2>&1
  fi
}

branch_out=$(branches_list) && branch_rc=0 || branch_rc=$?

if [ $branch_rc -eq 0 ]; then
  printf '  %s✓ branching is enabled on %s%s\n' "$GREEN" "$SUPABASE_PROJECT_ID" "$RESET"
  printf '%s\n' "$branch_out"
elif printf '%s' "$branch_out" | grep -q "401"; then
  warn "401 Unauthorized -- this profile cannot see project $SUPABASE_PROJECT_ID."
  warn "Wrong profile, or it was never authenticated."
  note "  switch:   npx supabase branches list --project-ref $SUPABASE_PROJECT_ID --profile <name>"
  # A profile is CREATED with `login --name`; it is SELECTED with `--profile`.
  note "  or create it: npx supabase login --name ${SUPABASE_PROFILE:-<name>}"
  SKIPPED+=("confirm branching -- 401 for profile '${SUPABASE_PROFILE:-default}'")
else
  warn "Could not list branches. Branching may not be enabled yet."
  note "$(printf '%s' "$branch_out" | head -3)"
  SKIPPED+=("confirm branching: npx supabase branches list --project-ref $SUPABASE_PROJECT_ID")
fi

finish
say "Open a PR to test: Supabase creates a preview branch, and the"
say "'Preview environment' workflow comments a pr.new link wired to it."
printf '\n'
