/**
 * App-facing row types, derived from the schema rather than hand-written.
 *
 * `supabase/db/database.types.ts` is generated by `deno task db:gen-types` and
 * is already the source of truth for the Edge Functions; the frontend now
 * shares it, so a dropped table or renamed column is a build error on both
 * sides instead of a runtime surprise.
 */

import type { Json, Tables } from "@db/database.types";

/** One place a notification can be delivered. Stored as jsonb on a monitor. */
export interface NotificationChannel {
  type: "email" | "sms";
  address: string;
  /** Client-side key for list rendering; not persisted meaningfully. */
  id?: string;
}

/**
 * monitors.notification_channels is jsonb, so the generated type is `Json` --
 * accurate about the column, useless at a call site. A monitor is a row with
 * that one column narrowed; use `toMonitor` to cross the boundary.
 */
export type Monitor = Omit<Tables<"monitors">, "notification_channels"> & {
  notification_channels: NotificationChannel[];
};

/**
 * jsonb means the database can hand back anything, including rows written by
 * an older version of this app. Drop entries that are not a channel rather
 * than letting a malformed one crash the render.
 */
function parseNotificationChannels(value: Json): NotificationChannel[] {
  if (!Array.isArray(value)) return [];
  return value.flatMap((entry) => {
    if (typeof entry !== "object" || entry === null || Array.isArray(entry)) {
      return [];
    }
    const { type, address } = entry as Record<string, unknown>;
    if (type !== "email" && type !== "sms") return [];
    if (typeof address !== "string") return [];
    return [{ type, address }];
  });
}

/** Narrow a monitors row as it comes out of the database. */
export function toMonitor(row: Tables<"monitors">): Monitor {
  return {
    ...row,
    notification_channels: parseNotificationChannels(row.notification_channels),
  };
}

/** The check-history fields the monitor card renders. */
export type MonitorLog = Pick<
  Tables<"monitor_logs">,
  | "id"
  | "status"
  | "response_time"
  | "error_message"
  | "content_snippet"
  | "checked_at"
>;

export type Profile = Tables<"profiles">;

/** A notification row plus the monitor it belongs to, when embedded. */
export type Notification = Tables<"notifications"> & {
  monitors?: Pick<Tables<"monitors">, "name" | "url"> | null;
};
