name: Deploy to Supabase Functions
on:
  push:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.5

      - name: Build step
        run: "deno task fns:checks"

      - run: supabase secrets set CURRENT_SHA=${{ github.sha }} --project-ref $PROJECT_ID

      - uses: supabase/setup-cli@v1
        with:
          version: latest
      # this is broken
      - run: supabase functions deploy --project-ref $PROJECT_ID
